language: node_js
node_js:
- 9.10.1

script:
- node deploy/tests/lint.js ./config/containers
- node deploy/tests/lint.js ./config/templates

deploy:
  provider: gcs
  access_key_id: GOOG4MC7HV5UPCV5HUMCBHRL
  secret_access_key:
    secure: unwvJO0AvgxdpwjDV8gLkPsF5A+CEEx/ejMef/AfjbBEb6DFrudNpDv55duhCfJkj89sVrvosF0MT4L7hCh34JGv53ZYTHZhLesiFnrAldsCGp8USAZNtT2Twah3e/PureSAbNJN1KshAPU5EkhgSkb4dHyNEDsZnbCaL1ACTJcUn+t41HAVsgcGoSz1B7v1Lj1ZKfCMN6x2ZbKO/UmZ15td1agSogmo+M7BG900V8ot0bvzSerzClFR88WpVJs9Z3teRD3CHExBv5KrfQ0ex7BdJqGXvRMyPw4diqkjKxERbuIYsNqCiSOrgJEfVqHjSLbqkt5AcVuJET8Pm9bzqZvMqEJpr5hv/D7ZQs4Ev3+fT/ANiG+6ExKwo9rRTwAoSZJWNaM/mJeoEJms39hzWLZGFETDfwUNWsb3T9WMsFm0OkKW5+K8pT8yxBLHQsLe8O1iio43hbqNlPSidfbO/32kcgLPVKOsLdvncDIl5jYtVFeqVSwMRGlfadLDPoq5rt8zVtnXKaQzpPMRkm0iKvMTdFWaQ62ERdXH7kPCGzODY2/Lhv/3y4Gyq5yS8E6PuvKru1pXAxvonQ7/G685ZtzDkuY1fUMWzZDnYH/wmef9pJ+rPhCQ4R2WKKT4gw9Rp83xDH/n4tXIp5arzC2Pu8eMZOeoSd4S68jQUutqyJs=
  bucket: okty-7e60c.appspot.com
  local-dir: config
  on:
    repo: Okty-io/okty-config
    branch: master